package com.example.myapplication.utils

object Constant {
    const val KEY_OPEN_SPLASH =  "KEY_OPEN_SPLASH"
    const val KEY_FROM_SPLASH =  "KEY_FROM_SPLASH"
    const val EXTRA_ADDRESS =  "EXTRA_ADDRESS"
    const val EXTRA_GROUP_ADDRESSES = "EXTRA_GROUP_ADDRESSES"
    const val EXTRA_SMS_NOTIFICATION_ADDRESS = "EXTRA_SMS_NOTIFICATION_ADDRESS"
    const val EXTRA_SMS_NOTIFICATION_BODY = "EXTRA_SMS_NOTIFICATION_BODY"
    const val EXTRA_OPEN_MESSENGER_FROM_NOTIFICATION = "EXTRA_OPEN_MESSENGER_FROM_NOTIFICATION"
    const val ACTION_SMS_SENT = "com.example.myapplication.SMS_SENT"
    const val EXTRA_MESSAGE_ID = "EXTRA_MESSAGE_ID"
    const val KEY_SP_CURRENT_THEME = "KEY_SP_CURRENT_THEME"
    const val EMAIL_ADDRESS = "support@example.com"
}
