package com.example.myapplication.domain.usecase

import com.example.myapplication.domain.layer.CategoryThemeModel
import com.example.myapplication.domain.layer.ThemeMessModel
import javax.inject.Inject

class GetListThemeUseCase @Inject constructor() :
    UseCase<GetListThemeUseCase.Param, List<CategoryThemeModel>>() {

    open class Param() : UseCase.Param()

    override suspend fun execute(param: Param): List<CategoryThemeModel> = listOf(
        CategoryThemeModel(
            nameCategory = "Basic",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/base/theme_base_1.png",
                    pathBG = "#FFFFFF",
                    pathAvt = "themes/base/avt_base_1.png",
                    pathBubbleSent = "themes/base/bb_sent_base_1.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_1.png",
                    pathEnterChat = "themes/base/enter_sent_base_1.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#1DAA61",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#D9FDD3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#1DAA61",
                    colBGEnterChat = "#D9FDD3",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/base/theme_base_2.png",
                    pathBG = "#FFB4B4",
                    pathAvt = "themes/base/avt_base_2.png",
                    pathBubbleSent = "themes/base/bb_sent_base_2.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_2.png",
                    pathEnterChat = "themes/base/enter_sent_base_2.png",
                    font = "fonts/PTSans-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#FFFFFF",
                    widthStroke = 1,
                    colMain = "#D92243",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#F8C6C6",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#D92243",
                    colBGEnterChat = "#F8C6C6",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/base/theme_base_3.png",
                    pathBG = "#FFFFFF",
                    pathAvt = "themes/base/avt_base_3.png",
                    pathBubbleSent = "themes/base/bb_sent_base_3.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_3.png",
                    pathEnterChat = "themes/base/enter_sent_base_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#1DAA61",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#D9FDD3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#1DAA61",
                    colBGEnterChat = "#D9FDD3",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/base/theme_base_1.png",
                    pathBG = "#FFFFFF",
                    pathAvt = "themes/base/avt_base_1.png",
                    pathBubbleSent = "themes/base/bb_sent_base_1.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_1.png",
                    pathEnterChat = "themes/base/enter_sent_base_1.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#1DAA61",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#D9FDD3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#1DAA61",
                    colBGEnterChat = "#D9FDD3",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/base/theme_base_1.png",
                    pathBG = "#FFFFFF",
                    pathAvt = "themes/base/avt_base_1.png",
                    pathBubbleSent = "themes/base/bb_sent_base_1.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_1.png",
                    pathEnterChat = "themes/base/enter_sent_base_1.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#1DAA61",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#D9FDD3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#1DAA61",
                    colBGEnterChat = "#D9FDD3",
                    colTextEnterChat = "#FFFFFF"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Romantic",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/romatic/ img_default_romantic_1.png",
                    pathBG = "themes/romatic/ img_bg_romantic_1.png",
                    pathAvt = "themes/romatic/ img_img_avt_romantic_1.png",
                    pathBubbleSent = "themes/romatic/ img_bg_bubble_sent_romantic_1.png",
                    pathBubbleReceived = "themes/romatic/ img_bg_bubble_receive_romantic_1.png",
                    pathEnterChat = "themes/romatic/ img_bg_write_mess_romatic_1.png",
                    font = "fonts/Livvic-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = true,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#000000",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFFFFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#000000",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/romatic/ img_default_romantic_2.png",
                    pathBG = "themes/romatic/ img_bg_romantic_2.png",
                    pathAvt = "themes/romatic/img_avt_romantic_2.png",
                    pathBubbleSent = "themes/romatic/ img_bg_bubble_sent_romantic_2.png",
                    pathBubbleReceived = "themes/romatic/ img_bg_bubble_receive_romantic_2.png",
                    pathEnterChat = "themes/romatic/ img_bg_write_mess_romatic_2.png",
                    font = "fonts/LobsterTwo-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#008CFF",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#ED3030",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#008CFF",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#008CFF"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/romatic/ img_default_romantic_3.png",
                    pathBG = "themes/romatic/ img_bg_romantic_3.png",
                    pathAvt = "themes/romatic/ img_img_avt_romantic_3.png",
                    pathBubbleSent = "themes/romatic/ img_bg_bubble_sent_romantic_3.png",
                    pathBubbleReceived = "themes/romatic/ img_bg_bubble_receive_romantic_3.png",
                    pathEnterChat = "themes/romatic/ img_bg_write_mess_romatic_3.png",
                    font = "fonts/LobsterTwo-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#F20539",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#D59E64",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#F20539",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#F20539"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/romatic/ img_default_romantic_4.png",
                    pathBG = "themes/romatic/ img_bg_romantic_4.png",
                    pathAvt = "themes/romatic/ img_img_avt_romantic_4.png",
                    pathBubbleSent = "themes/romatic/ img_bg_bubble_sent_romantic_4.png",
                    pathBubbleReceived = "themes/romatic/ img_bg_bubble_receive_romantic_4.png",
                    pathEnterChat = "themes/romatic/ img_bg_write_mess_romatic_4.png",
                    font = "fonts/LobsterTwo-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#680011",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#003A60",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#680011",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#680011"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/romatic/ img_default_romantic_5.png",
                    pathBG = "themes/romatic/ img_bg_romantic_5.png",
                    pathAvt = "themes/romatic/ img_img_avt_romantic_5.png",
                    pathBubbleSent = "themes/romatic/ img_bg_bubble_sent_romantic_5.png",
                    pathBubbleReceived = "themes/romatic/ img_bg_bubble_receive_romantic_5.png",
                    pathEnterChat = "themes/romatic/ img_bg_write_mess_romatic_5.png",
                    font = "fonts/LobsterTwo-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = true,
                    colorStroke = "#FF0004",
                    widthStroke = 2,
                    colMain = "#FF0004",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#4DC60003",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF0004",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#FF0004"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Animal",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/animal/ img_default_animal_1.png",
                    pathBG = "themes/animal/ img_bg_animal_1.png",
                    pathAvt = "themes/animal/ img_img_avt_animal_1.png",
                    pathBubbleSent = "themes/animal/ img_bg_bubble_sent_animal_1.png",
                    pathBubbleReceived = "themes/animal/ img_bg_bubble_receive_animal_1.png",
                    pathEnterChat = "themes/animal/ img_bg_write_mess_romatic_1.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = true,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#CF2B2A",
                    colStrokeBBReceived = "CF2B2A",
                    colTextBBReceived = "#CF2B2A",
                    colBGBBReceived = "#FFFFFF",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#CF2B2A",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#CF2B2A"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/animal/ img_default_animal_2.png",
                    pathBG = "themes/animal/ img_bg_animal_2.png",
                    pathAvt = "themes/animal/img_avatar_animal_2.png",
                    pathBubbleSent = "themes/animal/ img_bg_bubble_sent_animal_2.png",
                    pathBubbleReceived = "themes/animal/ img_bg_bubble_receive_animal_2.png",
                    pathEnterChat = "themes/animal/ img_bg_write_mess_romatic_2.png",
                    font = "fonts/LobsterTwo-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#FFFFFF",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#008CFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#008CFF",
                    colBGBBSent = "#FFFFFF",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#008CFF"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/animal/ img_default_animal_3.png",
                    pathBG = "themes/animal/ img_bg_animal_3.png",
                    pathAvt = "themes/animal/ img_img_avt_animal_3.png",
                    pathBubbleSent = "themes/animal/ img_bg_bubble_sent_animal_3.png",
                    pathBubbleReceived = "themes/animal/ img_bg_bubble_receive_animal_3.png",
                    pathEnterChat = "themes/animal/ img_bg_write_mess_animal_3.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#FFC8A8",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#02295A",
                    colStrokeBBSent = "",
                    colTextBBSent = "#000000",
                    colBGBBSent = "#F20539",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/animal/ img_default_animal_4.png",
                    pathBG = "themes/animal/ img_bg_animal_4.png",
                    pathAvt = "themes/animal/img_avatar_animal_4.png",
                    pathBubbleSent = "themes/animal/ img_bg_bubble_sent_animal_4.png",
                    pathBubbleReceived = "themes/animal/ img_bg_bubble_receive_animal_4.png",
                    pathEnterChat = "themes/animal/ img_bg_write_mess_animal_4.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#C74167",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#FE85A7",
                    colStrokeBBSent = "#D9D9D9",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#C74167",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#C74167"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/animal/ img_default_animal_5.png",
                    pathBG = "themes/animal/ img_bg_animal_5.png",
                    pathAvt = "themes/animal/img_avatar_animal_5.png",
                    pathBubbleSent = "themes/animal/ img_bg_bubble_sent_animal_5.png",
                    pathBubbleReceived = "themes/animal/ img_bg_bubble_receive_animal_5.png",
                    pathEnterChat = "themes/animal/ img_bg_write_mess_animal_5.png",
                    font = "fonts/LobsterTwo-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#ffffff",
                    widthStroke = 2,
                    colMain = "#95D707",
                    colStrokeBBReceived = "#FFFFFF",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#DA5638",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#95D707",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#95D707"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Nature",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/nature/ img_default_nature_1.png",
                    pathBG = "themes/nature/ img_bg_nature_1.png",
                    pathAvt = "themes/nature/ img_img_avt_nature_1.png",
                    pathBubbleSent = "themes/nature/ img_bg_bubble_sent_nature_1.png",
                    pathBubbleReceived = "themes/nature/ img_bg_bubble_receive_nature_1.png",
                    pathEnterChat = "themes/nature/ img_bg_write_mess_romatic_1.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#FFFFFF",
                    colStrokeBBReceived = "#FFFFFF",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#000000",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#5BD105",
                    colBGBBSent = "#FFFFFF",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/nature/ img_default_nature_2.png",
                    pathBG = "themes/nature/ img_bg_nature_2.png",
                    pathAvt = "themes/nature/img_avatar_nature_2.png",
                    pathBubbleSent = "themes/nature/ img_bg_bubble_sent_nature_2.png",
                    pathBubbleReceived = "themes/nature/ img_bg_bubble_receive_nature_2.png",
                    pathEnterChat = "themes/nature/ img_bg_write_mess_romatic_2.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#FFFFFF",
                    widthStroke = 1,
                    colMain = "#F770B2",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#729100",
                    colStrokeBBSent = "",
                    colTextBBSent = "#008CFF",
                    colBGBBSent = "#F770B2",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#F770B2"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/nature/ img_default_nature_3.png",
                    pathBG = "themes/nature/ img_bg_nature_3.png",
                    pathAvt = "themes/nature/ img_img_avt_nature_3.png",
                    pathBubbleSent = "themes/nature/ img_bg_bubble_sent_nature_3.png",
                    pathBubbleReceived = "themes/nature/ img_bg_bubble_receive_nature_3.png",
                    pathEnterChat = "themes/nature/ img_bg_write_mess_nature_3.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#8CE475",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#65A0C7",
                    colStrokeBBSent = "",
                    colTextBBSent = "#000000",
                    colBGBBSent = "#8CE475",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#8CE475"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/nature/ img_default_nature_4.png",
                    pathBG = "themes/nature/ img_bg_nature_4.png",
                    pathAvt = "themes/nature/img_avatar_nature_4.png",
                    pathBubbleSent = "themes/nature/ img_bg_bubble_sent_nature_4.png",
                    pathBubbleReceived = "themes/nature/ img_bg_bubble_receive_nature_4.png",
                    pathEnterChat = "themes/nature/ img_bg_write_mess_nature_4.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#000000",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#61CCB8",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#000000",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/nature/ img_default_nature_5.png",
                    pathBG = "themes/nature/ img_bg_nature_5.png",
                    pathAvt = "themes/nature/img_avatar_nature_5.png",
                    pathBubbleSent = "themes/nature/ img_bg_bubble_sent_nature_5.png",
                    pathBubbleReceived = "themes/nature/ img_bg_bubble_receive_nature_5.png",
                    pathEnterChat = "themes/nature/ img_bg_write_mess_nature_5.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#ffffff",
                    widthStroke = 2,
                    colMain = "#4B3843",
                    colStrokeBBReceived = "#FFFFFF",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#B12F90",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#4B3843",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#4B3843"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Car",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/car/ img_default_car_1.png",
                    pathBG = "themes/car/ img_bg_car_1.png",
                    pathAvt = "themes/car/ img_img_avt_car_1.png",
                    pathBubbleSent = "themes/car/ img_bg_bubble_sent_car_1.png",
                    pathBubbleReceived = "themes/car/ img_bg_bubble_receive_car_1.png",
                    pathEnterChat = "themes/car/ img_bg_write_mess_romatic_1.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#FF4C00",
                    colStrokeBBReceived = "#FFFFFF",
                    colTextBBReceived = "#FF4C00",
                    colBGBBReceived = "#FFFFFF",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF4C00",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#FF4C00"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/car/ img_default_car_2.png",
                    pathBG = "themes/car/ img_bg_car_2.png",
                    pathAvt = "themes/car/img_avatar_car_2.png",
                    pathBubbleSent = "themes/car/ img_bg_bubble_sent_car_2.png",
                    pathBubbleReceived = "themes/car/ img_bg_bubble_receive_car_2.png",
                    pathEnterChat = "themes/car/ img_bg_write_mess_romatic_2.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 1,
                    colMain = "#9EFF00",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#ADB2B8",
                    colStrokeBBSent = "",
                    colTextBBSent = "#000000",
                    colBGBBSent = "#9EFF00",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#9EFF00"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/car/ img_default_car_3.png",
                    pathBG = "themes/car/ img_bg_car_3.png",
                    pathAvt = "themes/car/ img_img_avt_car_3.png",
                    pathBubbleSent = "themes/car/ img_bg_bubble_sent_car_3.png",
                    pathBubbleReceived = "themes/car/ img_bg_bubble_receive_car_3.png",
                    pathEnterChat = "themes/car/ img_bg_write_mess_car_3.png",
                    font = "fonts/Arya-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#0463A3",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#9AA6B1",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#0463A3",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#0463A3"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/car/ img_default_car_4.png",
                    pathBG = "themes/car/ img_bg_car_4.png",
                    pathAvt = "themes/car/ img_img_avt_car_4.png",
                    pathBubbleSent = "themes/car/ img_bg_bubble_sent_car_4.png",
                    pathBubbleReceived = "themes/car/ img_bg_bubble_receive_car_4.png",
                    pathEnterChat = "themes/car/ img_bg_write_mess_car_4.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#FF7700",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#6E5E4B",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF7700",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#FF7700"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/car/ img_default_car_5.png",
                    pathBG = "themes/car/img_avatar_car_5.png",
                    pathAvt = "themes/car/ img_img_avt_car_5.png",
                    pathBubbleSent = "themes/car/ img_bg_bubble_sent_car_5.png",
                    pathBubbleReceived = "themes/car/ img_bg_bubble_receive_car_5.png",
                    pathEnterChat = "themes/car/ img_bg_write_mess_car_5.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#ffffff",
                    widthStroke = 2,
                    colMain = "#0092FF",
                    colStrokeBBReceived = "#FFFFFF",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#000000",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#0092FF",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#0092FF"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Cartoon",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/cartoon/ img_default_cartoon_1.png",
                    pathBG = "themes/cartoon/ img_bg_cartoon_1.png",
                    pathAvt = "themes/cartoon/img_avatar_cartoon_1.png",
                    pathBubbleSent = "themes/cartoon/ img_bg_bubble_sent_cartoon_1.png",
                    pathBubbleReceived = "themes/cartoon/ img_bg_bubble_receive_cartoon_1.png",
                    pathEnterChat = "themes/cartoon/ img_bg_write_mess_romatic_1.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#0057FF",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#C59C2F",
                    colBGBBReceived = "#FFFFFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#0057FF",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#0057FF"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/cartoon/ img_default_cartoon_2.png",
                    pathBG = "themes/cartoon/ img_bg_cartoon_2.png",
                    pathAvt = "themes/cartoon/ img_img_avt_cartoon_2.png",
                    pathBubbleSent = "themes/cartoon/ img_bg_bubble_sent_cartoon_2.png",
                    pathBubbleReceived = "themes/cartoon/ img_bg_bubble_receive_cartoon_2.png",
                    pathEnterChat = "themes/cartoon/ img_bg_write_mess_romatic_2.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 1,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 1,
                    colMain = "#008CFF",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#F68A66",
                    colStrokeBBSent = "",
                    colTextBBSent = "#008CFF",
                    colBGBBSent = "#FFFFFF",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#008CFF"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/cartoon/ img_default_cartoon_3.png",
                    pathBG = "themes/cartoon/ img_bg_cartoon_3.png",
                    pathAvt = "themes/cartoon/ img_img_avt_cartoon_3.png",
                    pathBubbleSent = "themes/cartoon/ img_bg_bubble_sent_cartoon_3.png",
                    pathBubbleReceived = "themes/cartoon/ img_bg_bubble_receive_cartoon_3.png",
                    pathEnterChat = "themes/cartoon/ img_bg_write_mess_cartoon_3.png",
                    font = "fonts/Arya-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = false,
                    colorStroke = "#000000",
                    widthStroke = 2,
                    colMain = "#9A27E5",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#4B678D",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#9A27E5",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#9A27E5"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/cartoon/ img_default_cartoon_4.png",
                    pathBG = "themes/cartoon/ img_bg_cartoon_4.png",
                    pathAvt = "themes/cartoon/ img_img_avt_cartoon_4.png",
                    pathBubbleSent = "themes/cartoon/ img_bg_bubble_sent_cartoon_4.png",
                    pathBubbleReceived = "themes/cartoon/ img_bg_bubble_receive_cartoon_4.png",
                    pathEnterChat = "themes/cartoon/ img_bg_write_mess_cartoon_4.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = true,
                    colorStroke = "#FFFFFF",
                    widthStroke = 2,
                    colMain = "#3E790B",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#1EA59E",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#3E790B",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#3E790B"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/cartoon/ img_default_cartoon_5.png",
                    pathBG = "themes/cartoon/ img_bg_cartoon_5.png",
                    pathAvt = "themes/cartoon/img_avatar_cartoon_5.png",
                    pathBubbleSent = "themes/cartoon/ img_bg_bubble_sent_cartoon_5.png",
                    pathBubbleReceived = "themes/cartoon/ img_bg_bubble_receive_cartoon_5.png",
                    pathEnterChat = "themes/cartoon/ img_bg_write_mess_cartoon_5.png",
                    font = "fonts/PTSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = true,
                    colorStroke = "#ffffff",
                    widthStroke = 2,
                    colMain = "#008AFF",
                    colStrokeBBReceived = "#FFFFFF",
                    colTextBBReceived = "#FFFFFF",
                    colBGBBReceived = "#FF8A00",
                    colStrokeBBSent = "#FFFFFF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#008AFF",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#008AFF"
                ),
            )
        ),
//        CategoryThemeModel(
//            nameCategory = "Football",
//            listTheme = listOf(
//                ThemeMessModel(
//                    id = 0,
//                    pathThemePreview = "themes/basic/img_default_basic_1.png",
//                    pathBG = "themes/basic/img_bg_basic_1.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_1.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_1.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_1.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_1.png",
//                    font = "fonts/NotoSans-Bold.ttf",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    colMain = "#008CFF",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#AAAAAA",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#008CFF",
//                    colBGEnterChat = "#B6DEFF",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 1,
//                    pathThemePreview = "themes/basic/img_default_basic_2.png",
//                    pathBG = "themes/basic/img_bg_basic_2.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_2.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_2.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_2.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_2.png",
//                    typeBubble = 0,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Oregano-Regular.ttf",
//                    colMain = "#EF305F",
//                    colStrokeBBReceived = "#EF305F",
//                    colTextBBReceived = "#EF305F",
//                    colBGBBReceived = "#FFFFFF",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#EF305F",
//                    colBGEnterChat = "#FFACC3",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 2,
//                    pathThemePreview = "themes/basic/img_default_basic_3.png",
//                    pathBG = "themes/basic/img_bg_basic_3.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_3.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_3.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_3.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_3.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Numans-Regular.ttf",
//                    colMain = "#0094E8",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#A4C0CE",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#0094E8",
//                    colBGEnterChat = "#87B7D2",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 3,
//                    pathThemePreview = "themes/basic/img_default_basic_4.png",
//                    pathBG = "themes/basic/img_bg_basic_4.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_4.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_4.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_4.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_4.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/PTSans-Bold.ttf",
//                    colMain = "#6F8D00",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#197D82",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#6F8D00",
//                    colBGEnterChat = "##197D82",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 4,
//                    pathThemePreview = "themes/basic/img_default_basic_5.png",
//                    pathBG = "themes/basic/img_bg_basic_5.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_5.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_5.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_5.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_5.png",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    font = "fonts/Mulish-Bold.ttf",
//                    colMain = "#105F9B",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#000000",
//                    colBGBBReceived = "#BACBDD",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#105F9B",
//                    colBGEnterChat = "#5FAFEB",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//            )
//
//        ),
//        CategoryThemeModel(
//            nameCategory = "Anime",
//            listTheme = listOf(
//                ThemeMessModel(
//                    id = 0,
//                    pathThemePreview = "themes/basic/img_default_basic_1.png",
//                    pathBG = "themes/basic/img_bg_basic_1.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_1.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_1.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_1.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_1.png",
//                    font = "fonts/NotoSans-Bold.ttf",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    colMain = "#008CFF",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#AAAAAA",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#008CFF",
//                    colBGEnterChat = "#B6DEFF",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 1,
//                    pathThemePreview = "themes/basic/img_default_basic_2.png",
//                    pathBG = "themes/basic/img_bg_basic_2.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_2.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_2.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_2.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_2.png",
//                    typeBubble = 0,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Oregano-Regular.ttf",
//                    colMain = "#EF305F",
//                    colStrokeBBReceived = "#EF305F",
//                    colTextBBReceived = "#EF305F",
//                    colBGBBReceived = "#FFFFFF",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#EF305F",
//                    colBGEnterChat = "#FFACC3",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 2,
//                    pathThemePreview = "themes/basic/img_default_basic_3.png",
//                    pathBG = "themes/basic/img_bg_basic_3.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_3.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_3.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_3.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_3.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Numans-Regular.ttf",
//                    colMain = "#0094E8",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#A4C0CE",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#0094E8",
//                    colBGEnterChat = "#87B7D2",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 3,
//                    pathThemePreview = "themes/basic/img_default_basic_4.png",
//                    pathBG = "themes/basic/img_bg_basic_4.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_4.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_4.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_4.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_4.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/PTSans-Bold.ttf",
//                    colMain = "#6F8D00",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#197D82",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#6F8D00",
//                    colBGEnterChat = "##197D82",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 4,
//                    pathThemePreview = "themes/basic/img_default_basic_5.png",
//                    pathBG = "themes/basic/img_bg_basic_5.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_5.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_5.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_5.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_5.png",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    font = "fonts/Mulish-Bold.ttf",
//                    colMain = "#105F9B",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#000000",
//                    colBGBBReceived = "#BACBDD",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#105F9B",
//                    colBGEnterChat = "#5FAFEB",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//            )
//
//        ),
//        CategoryThemeModel(
//            nameCategory = "Flower",
//            listTheme = listOf(
//                ThemeMessModel(
//                    id = 0,
//                    pathThemePreview = "themes/basic/img_default_basic_1.png",
//                    pathBG = "themes/basic/img_bg_basic_1.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_1.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_1.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_1.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_1.png",
//                    font = "fonts/NotoSans-Bold.ttf",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    colMain = "#008CFF",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#AAAAAA",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#008CFF",
//                    colBGEnterChat = "#B6DEFF",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 1,
//                    pathThemePreview = "themes/basic/img_default_basic_2.png",
//                    pathBG = "themes/basic/img_bg_basic_2.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_2.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_2.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_2.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_2.png",
//                    typeBubble = 0,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Oregano-Regular.ttf",
//                    colMain = "#EF305F",
//                    colStrokeBBReceived = "#EF305F",
//                    colTextBBReceived = "#EF305F",
//                    colBGBBReceived = "#FFFFFF",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#EF305F",
//                    colBGEnterChat = "#FFACC3",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 2,
//                    pathThemePreview = "themes/basic/img_default_basic_3.png",
//                    pathBG = "themes/basic/img_bg_basic_3.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_3.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_3.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_3.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_3.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Numans-Regular.ttf",
//                    colMain = "#0094E8",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#A4C0CE",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#0094E8",
//                    colBGEnterChat = "#87B7D2",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 3,
//                    pathThemePreview = "themes/basic/img_default_basic_4.png",
//                    pathBG = "themes/basic/img_bg_basic_4.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_4.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_4.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_4.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_4.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/PTSans-Bold.ttf",
//                    colMain = "#6F8D00",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#197D82",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#6F8D00",
//                    colBGEnterChat = "##197D82",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 4,
//                    pathThemePreview = "themes/basic/img_default_basic_5.png",
//                    pathBG = "themes/basic/img_bg_basic_5.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_5.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_5.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_5.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_5.png",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    font = "fonts/Mulish-Bold.ttf",
//                    colMain = "#105F9B",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#000000",
//                    colBGBBReceived = "#BACBDD",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#105F9B",
//                    colBGEnterChat = "#5FAFEB",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//            )
//
//        ),
//        CategoryThemeModel(
//            nameCategory = "Holiday",
//            listTheme = listOf(
//                ThemeMessModel(
//                    id = 0,
//                    pathThemePreview = "themes/basic/img_default_basic_1.png",
//                    pathBG = "themes/basic/img_bg_basic_1.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_1.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_1.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_1.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_1.png",
//                    font = "fonts/NotoSans-Bold.ttf",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    colMain = "#008CFF",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#AAAAAA",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#008CFF",
//                    colBGEnterChat = "#B6DEFF",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 1,
//                    pathThemePreview = "themes/basic/img_default_basic_2.png",
//                    pathBG = "themes/basic/img_bg_basic_2.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_2.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_2.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_2.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_2.png",
//                    typeBubble = 0,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Oregano-Regular.ttf",
//                    colMain = "#EF305F",
//                    colStrokeBBReceived = "#EF305F",
//                    colTextBBReceived = "#EF305F",
//                    colBGBBReceived = "#FFFFFF",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#EF305F",
//                    colBGEnterChat = "#FFACC3",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 2,
//                    pathThemePreview = "themes/basic/img_default_basic_3.png",
//                    pathBG = "themes/basic/img_bg_basic_3.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_3.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_3.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_3.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_3.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Numans-Regular.ttf",
//                    colMain = "#0094E8",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#A4C0CE",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#0094E8",
//                    colBGEnterChat = "#87B7D2",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 3,
//                    pathThemePreview = "themes/basic/img_default_basic_4.png",
//                    pathBG = "themes/basic/img_bg_basic_4.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_4.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_4.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_4.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_4.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/PTSans-Bold.ttf",
//                    colMain = "#6F8D00",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#197D82",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#6F8D00",
//                    colBGEnterChat = "##197D82",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 4,
//                    pathThemePreview = "themes/basic/img_default_basic_5.png",
//                    pathBG = "themes/basic/img_bg_basic_5.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_5.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_5.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_5.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_5.png",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    font = "fonts/Mulish-Bold.ttf",
//                    colMain = "#105F9B",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#000000",
//                    colBGBBReceived = "#BACBDD",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#105F9B",
//                    colBGEnterChat = "#5FAFEB",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//            )
//
//        ),
//        CategoryThemeModel(
//            nameCategory = "Plane",
//            listTheme = listOf(
//                ThemeMessModel(
//                    id = 0,
//                    pathThemePreview = "themes/basic/img_default_basic_1.png",
//                    pathBG = "themes/basic/img_bg_basic_1.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_1.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_1.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_1.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_1.png",
//                    font = "fonts/NotoSans-Bold.ttf",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    colMain = "#008CFF",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#AAAAAA",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#008CFF",
//                    colBGEnterChat = "#B6DEFF",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 1,
//                    pathThemePreview = "themes/basic/img_default_basic_2.png",
//                    pathBG = "themes/basic/img_bg_basic_2.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_2.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_2.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_2.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_2.png",
//                    typeBubble = 0,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Oregano-Regular.ttf",
//                    colMain = "#EF305F",
//                    colStrokeBBReceived = "#EF305F",
//                    colTextBBReceived = "#EF305F",
//                    colBGBBReceived = "#FFFFFF",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#EF305F",
//                    colBGEnterChat = "#FFACC3",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 2,
//                    pathThemePreview = "themes/basic/img_default_basic_3.png",
//                    pathBG = "themes/basic/img_bg_basic_3.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_3.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_3.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_3.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_3.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/Numans-Regular.ttf",
//                    colMain = "#0094E8",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#A4C0CE",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#0094E8",
//                    colBGEnterChat = "#87B7D2",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 3,
//                    pathThemePreview = "themes/basic/img_default_basic_4.png",
//                    pathBG = "themes/basic/img_bg_basic_4.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_4.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_4.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_4.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_4.png",
//                    typeBubble = 1,
//                    enableStroke = true,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 2,
//                    font = "fonts/PTSans-Bold.ttf",
//                    colMain = "#6F8D00",
//                    colStrokeBBReceived = "#FFFFFF",
//                    colTextBBReceived = "#FFFFFF",
//                    colBGBBReceived = "#197D82",
//                    colStrokeBBSent = "#FFFFFF",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#6F8D00",
//                    colBGEnterChat = "##197D82",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//                ThemeMessModel(
//                    id = 4,
//                    pathThemePreview = "themes/basic/img_default_basic_5.png",
//                    pathBG = "themes/basic/img_bg_basic_5.png",
//                    pathAvt = "themes/basic/img_img_avt_basic_5.png",
//                    pathBubbleSent = "themes/basic/img_bg_bubble_sent_basic_5.png",
//                    pathBubbleReceived = "themes/basic/img_bg_bubble_receive_basic_5.png",
//                    pathEnterChat = "themes/basic/img_bg_write_mess_basic_5.png",
//                    typeBubble = 0,
//                    enableStroke = false,
//                    colorStroke = "#FFFFFF",
//                    widthStroke = 0,
//                    font = "fonts/Mulish-Bold.ttf",
//                    colMain = "#105F9B",
//                    colStrokeBBReceived = "",
//                    colTextBBReceived = "#000000",
//                    colBGBBReceived = "#BACBDD",
//                    colStrokeBBSent = "",
//                    colTextBBSent = "#FFFFFF",
//                    colBGBBSent = "#105F9B",
//                    colBGEnterChat = "#5FAFEB",
//                    colTextEnterChat = "#FFFFFF"
//                ),
//            )
//
//        ),
    )
}