package com.example.myapplication.domain.usecase

import com.example.myapplication.domain.layer.CategoryThemeModel
import com.example.myapplication.domain.layer.ThemeMessModel
import javax.inject.Inject

class GetListThemeUseCase @Inject constructor() :
    UseCase<GetListThemeUseCase.Param, List<CategoryThemeModel>>() {

    open class Param() : UseCase.Param()

    override suspend fun execute(param: Param): List<CategoryThemeModel> = listOf(
        CategoryThemeModel(
            nameCategory = "Basic",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/base/theme_base_1.png",
                    pathBG = "#FFFFFF",
                    pathAvt = "themes/base/avt_base_1.png",
                    pathBubbleSent = "themes/base/bb_sent_base_1.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_1.png",
                    pathEnterChat = "themes/base/enter_sent_base_1.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#1DAA61",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#D9FDD3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#1DAA61",
                    colBGEnterChat = "#D9FDD3",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/base/theme_base_2.png",
                    pathBG = "#FFB4B4",
                    pathAvt = "themes/base/avt_base_2.png",
                    pathBubbleSent = "themes/base/bb_sent_base_2.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_2.png",
                    pathEnterChat = "themes/base/enter_sent_base_2.png",
                    font = "fonts/PTSans-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#FFFFFF",
                    widthStroke = 1,
                    colMain = "#D92243",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#F8C6C6",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#D92243",
                    colBGEnterChat = "#F8C6C6",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/base/theme_base_3.png",
                    pathBG = "#FFC093",
                    pathAvt = "themes/base/avt_base_3.png",
                    pathBubbleSent = "themes/base/bb_sent_base_3.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_3.png",
                    pathEnterChat = "themes/base/enter_sent_base_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FF7600",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFDFC3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF7600",
                    colBGEnterChat = "#FFDFC3",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/base/theme_base_4.png",
                    pathBG = "#FFC2E2",
                    pathAvt = "themes/base/avt_base_4.png",
                    pathBubbleSent = "themes/base/bb_sent_base_4.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_4.png",
                    pathEnterChat = "themes/base/enter_sent_base_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#D6336C",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFA9C7",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#D6336C",
                    colBGEnterChat = "#FFA9C7",
                    colTextEnterChat = "#FFFFFF"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/base/theme_base_5.png",
                    pathBG = "#97D8FF",
                    pathAvt = "themes/base/avt_base_5.png",
                    pathBubbleSent = "themes/base/bb_sent_base_5.png",
                    pathBubbleReceived = "themes/base/bb_receive_base_5.png",
                    pathEnterChat = "themes/base/enter_sent_base_5.png",
                    font = "fonts/PTSans-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#0091E9",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#CEECFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#0091E9",
                    colBGEnterChat = "#CEECFF",
                    colTextEnterChat = "#FFFFFF"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Robo",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/robo/theme_robo_1.png",
                    pathBG = "themes/robo/bg_robo_1.png",
                    pathAvt = "themes/robo/avt_robo_1.png",
                    pathBubbleSent = "themes/robo/bb_sent_robo_1.png",
                    pathBubbleReceived = "themes/robo/bb_receive_robo_1.png",
                    pathEnterChat = "themes/robo/enter_sent_robo_1.png",
                    font = "fonts/Podkova-VariableFont_wght.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FF0000",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#F6E3D3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF0000",
                    colBGEnterChat = "#F6E3D3",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/robo/theme_robo_2.png",
                    pathBG = "themes/robo/bg_robo_2.png",
                    pathAvt = "themes/robo/avt_robo_2.png",
                    pathBubbleSent = "themes/robo/bb_sent_robo_2.png",
                    pathBubbleReceived = "themes/robo/bb_receive_robo_2.png",
                    pathEnterChat = "themes/robo/enter_sent_robo_2.png",
                    font = "fonts/Martel-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#FFE6F1",
                    widthStroke = 1,
                    colMain = "#FF4FA3",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFE6F1",
                    colStrokeBBSent = "FFE6F1",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF4FA3",
                    colBGEnterChat = "#FFE6F1",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/robo/theme_robo_3.png",
                    pathBG = "themes/robo/bg_robo_3.png",
                    pathAvt = "themes/robo/avt_robo_3.png",
                    pathBubbleSent = "themes/robo/bb_sent_robo_3.png",
                    pathBubbleReceived = "themes/robo/bb_receive_robo_3.png",
                    pathEnterChat = "themes/robo/enter_sent_robo_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FFA43D",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFDCCF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FFA43D",
                    colBGEnterChat = "#FFDCCF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/robo/theme_robo_4.png",
                    pathBG = "themes/robo/bg_robo_4.png",
                    pathAvt = "themes/robo/avt_robo_4.png",
                    pathBubbleSent = "themes/robo/bb_sent_robo_4.png",
                    pathBubbleReceived = "themes/robo/bb_receive_robo_4.png",
                    pathEnterChat = "themes/robo/enter_sent_robo_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#2F8CFF",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#D9ECFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#2F8CFF",
                    colBGEnterChat = "#D9ECFF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/robo/theme_robo_5.png",
                    pathBG = "themes/robo/bg_robo_5.png",
                    pathAvt = "themes/robo/avt_robo_5.png",
                    pathBubbleSent = "themes/robo/bb_sent_robo_5.png",
                    pathBubbleReceived = "themes/robo/bb_receive_robo_5.png",
                    pathEnterChat = "themes/robo/enter_sent_robo_5.png",
                    font = "fonts/NotoSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#0094B2",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#DDECEF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#0094B2",
                    colBGEnterChat = "#DDECEF",
                    colTextEnterChat = "#000000"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Kawaii",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/kawaii/theme_kawaii_1.png",
                    pathBG = "themes/kawaii/bg_kawaii_1.png",
                    pathAvt = "themes/kawaii/avt_kawaii_1.png",
                    pathBubbleSent = "themes/kawaii/bb_sent_kawaii_1.png",
                    pathBubbleReceived = "themes/kawaii/bb_receive_kawaii_1.png",
                    pathEnterChat = "themes/kawaii/enter_sent_kawaii_1.png",
                    font = "fonts/Podkova-VariableFont_wght.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FF7A59",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFD0B2",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF7A59",
                    colBGEnterChat = "#FFD0B2",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/kawaii/theme_kawaii_2.png",
                    pathBG = "themes/kawaii/bg_kawaii_2.png",
                    pathAvt = "themes/kawaii/avt_kawaii_2.png",
                    pathBubbleSent = "themes/kawaii/bb_sent_kawaii_2.png",
                    pathBubbleReceived = "themes/kawaii/bb_receive_kawaii_2.png",
                    pathEnterChat = "themes/kawaii/enter_sent_kawaii_2.png",
                    font = "fonts/Martel-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#FF9DCC",
                    widthStroke = 1,
                    colMain = "#DB086E",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FF9DCC",
                    colStrokeBBSent = "FF9DCC",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#DB086E",
                    colBGEnterChat = "#FF9DCC",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/kawaii/theme_kawaii_3.png",
                    pathBG = "themes/kawaii/bg_kawaii_3.png",
                    pathAvt = "themes/kawaii/avt_kawaii_3.png",
                    pathBubbleSent = "themes/kawaii/bb_sent_kawaii_3.png",
                    pathBubbleReceived = "themes/kawaii/bb_receive_kawaii_3.png",
                    pathEnterChat = "themes/kawaii/enter_sent_kawaii_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FF4D00",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFBB97",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF4D00",
                    colBGEnterChat = "#FFBB97",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/kawaii/theme_kawaii_4.png",
                    pathBG = "themes/kawaii/bg_kawaii_4.png",
                    pathAvt = "themes/kawaii/avt_kawaii_4.png",
                    pathBubbleSent = "themes/kawaii/bb_sent_kawaii_4.png",
                    pathBubbleReceived = "themes/kawaii/bb_receive_kawaii_4.png",
                    pathEnterChat = "themes/kawaii/enter_sent_kawaii_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#0075E5",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#ACD6FF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#0075E5",
                    colBGEnterChat = "#ACD6FF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/kawaii/theme_kawaii_5.png",
                    pathBG = "themes/kawaii/bg_kawaii_5.png",
                    pathAvt = "themes/kawaii/avt_kawaii_5.png",
                    pathBubbleSent = "themes/kawaii/bb_sent_kawaii_5.png",
                    pathBubbleReceived = "themes/kawaii/bb_receive_kawaii_5.png",
                    pathEnterChat = "themes/kawaii/enter_sent_kawaii_5.png",
                    font = "fonts/NotoSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#3B6D7C",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#C9F3FF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#3B6D7C",
                    colBGEnterChat = "#C9F3FF",
                    colTextEnterChat = "#000000"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Girl",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/girl/theme_girl_1.png",
                    pathBG = "themes/girl/bg_girl_1.png",
                    pathAvt = "themes/girl/avt_girl_1.png",
                    pathBubbleSent = "themes/girl/bb_sent_girl_1.png",
                    pathBubbleReceived = "themes/girl/bb_receive_girl_1.png",
                    pathEnterChat = "themes/girl/enter_sent_girl_1.png",
                    font = "fonts/Podkova-VariableFont_wght.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FF5A36",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFD7C7",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF5A36",
                    colBGEnterChat = "#FFD7C7",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/girl/theme_girl_2.png",
                    pathBG = "themes/girl/bg_girl_2.png",
                    pathAvt = "themes/girl/avt_girl_2.png",
                    pathBubbleSent = "themes/girl/bb_sent_girl_2.png",
                    pathBubbleReceived = "themes/girl/bb_receive_girl_2.png",
                    pathEnterChat = "themes/girl/enter_sent_girl_2.png",
                    font = "fonts/Martel-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#DCE5FF",
                    widthStroke = 1,
                    colMain = "#4D7CFF",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#DCE5FF",
                    colStrokeBBSent = "DCE5FF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#4D7CFF",
                    colBGEnterChat = "#DCE5FF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/girl/theme_girl_3.png",
                    pathBG = "themes/girl/bg_girl_3.png",
                    pathAvt = "themes/girl/avt_girl_3.png",
                    pathBubbleSent = "themes/girl/bb_sent_girl_3.png",
                    pathBubbleReceived = "themes/girl/bb_receive_girl_3.png",
                    pathEnterChat = "themes/girl/enter_sent_girl_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#C8103A",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#DDE3F7",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#C8103A",
                    colBGEnterChat = "#DDE3F7",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/girl/theme_girl_4.png",
                    pathBG = "themes/girl/bg_girl_4.png",
                    pathAvt = "themes/girl/avt_girl_4.png",
                    pathBubbleSent = "themes/girl/bb_sent_girl_4.png",
                    pathBubbleReceived = "themes/girl/bb_receive_girl_4.png",
                    pathEnterChat = "themes/girl/enter_sent_girl_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FF6A00",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFE5D3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF6A00",
                    colBGEnterChat = "#FFE5D3",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/girl/theme_girl_5.png",
                    pathBG = "themes/girl/bg_girl_5.png",
                    pathAvt = "themes/girl/avt_girl_5.png",
                    pathBubbleSent = "themes/girl/bb_sent_girl_5.png",
                    pathBubbleReceived = "themes/girl/bb_receive_girl_5.png",
                    pathEnterChat = "themes/girl/enter_sent_girl_5.png",
                    font = "fonts/NotoSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#145D75",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#DDFCF7",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#145D75",
                    colBGEnterChat = "#DDFCF7",
                    colTextEnterChat = "#000000"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Cute",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/cute/theme_cute_1.png",
                    pathBG = "themes/cute/bg_cute_1.png",
                    pathAvt = "themes/cute/avt_cute_1.png",
                    pathBubbleSent = "themes/cute/bb_sent_cute_1.png",
                    pathBubbleReceived = "themes/cute/bb_receive_cute_1.png",
                    pathEnterChat = "themes/cute/enter_sent_cute_1.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#D32570",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFB4D4",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#D32570",
                    colBGEnterChat = "#FFB4D4",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/cute/theme_cute_2.png",
                    pathBG = "themes/cute/bg_cute_2.png",
                    pathAvt = "themes/cute/avt_cute_2.png",
                    pathBubbleSent = "themes/cute/bb_sent_cute_2.png",
                    pathBubbleReceived = "themes/cute/bb_receive_cute_2.png",
                    pathEnterChat = "themes/cute/enter_sent_cute_2.png",
                    font = "fonts/PTSans-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#DAFFD8",
                    widthStroke = 1,
                    colMain = "#156610",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#DAFFD8",
                    colStrokeBBSent = "DAFFD8",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#156610",
                    colBGEnterChat = "#DAFFD8",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/cute/theme_cute_3.png",
                    pathBG = "themes/cute/bg_cute_3.png",
                    pathAvt = "themes/cute/avt_cute_3.png",
                    pathBubbleSent = "themes/cute/bb_sent_cute_3.png",
                    pathBubbleReceived = "themes/cute/bb_receive_cute_3.png",
                    pathEnterChat = "themes/cute/enter_sent_cute_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#744577",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FBC2FF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#744577",
                    colBGEnterChat = "#FBC2FF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/cute/theme_cute_4.png",
                    pathBG = "themes/cute/bg_cute_4.png",
                    pathAvt = "themes/cute/avt_cute_4.png",
                    pathBubbleSent = "themes/cute/bb_sent_cute_4.png",
                    pathBubbleReceived = "themes/cute/bb_receive_cute_4.png",
                    pathEnterChat = "themes/cute/enter_sent_cute_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#B40000",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFC3C3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#B40000",
                    colBGEnterChat = "#FFC3C3",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/cute/theme_cute_5.png",
                    pathBG = "themes/cute/bg_cute_5.png",
                    pathAvt = "themes/cute/avt_cute_5.png",
                    pathBubbleSent = "themes/cute/bb_sent_cute_5.png",
                    pathBubbleReceived = "themes/cute/bb_receive_cute_5.png",
                    pathEnterChat = "themes/cute/enter_sent_cute_5.png",
                    font = "fonts/NotoSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#DA5B00",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFCFAD",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#DA5B00",
                    colBGEnterChat = "#FFCFAD",
                    colTextEnterChat = "#000000"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Football",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/football/theme_football_1.png",
                    pathBG = "themes/football/bg_football_1.png",
                    pathAvt = "themes/football/avt_football_1.png",
                    pathBubbleSent = "themes/football/bb_sent_football_1.png",
                    pathBubbleReceived = "themes/football/bb_receive_football_1.png",
                    pathEnterChat = "themes/football/enter_sent_football_1.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#DA0E00",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFB4B5",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#DA0E00",
                    colBGEnterChat = "#FFB4B5",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/football/theme_football_2.png",
                    pathBG = "themes/football/bg_football_2.png",
                    pathAvt = "themes/football/avt_football_2.png",
                    pathBubbleSent = "themes/football/bb_sent_football_2.png",
                    pathBubbleReceived = "themes/football/bb_receive_football_2.png",
                    pathEnterChat = "themes/football/enter_sent_football_2.png",
                    font = "fonts/PTSans-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#BEE1FF",
                    widthStroke = 1,
                    colMain = "#007DEA",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#BEE1FF",
                    colStrokeBBSent = "BEE1FF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#007DEA",
                    colBGEnterChat = "#BEE1FF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/football/theme_football_3.png",
                    pathBG = "themes/football/bg_football_3.png",
                    pathAvt = "themes/football/avt_football_3.png",
                    pathBubbleSent = "themes/football/bb_sent_football_3.png",
                    pathBubbleReceived = "themes/football/bb_receive_football_3.png",
                    pathEnterChat = "themes/football/enter_sent_football_3.png",
                    font = "fonts/Martel-Regular.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#DABA04",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFFFFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#DABA04",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/football/theme_football_4.png",
                    pathBG = "themes/football/bg_football_4.png",
                    pathAvt = "themes/football/avt_football_4.png",
                    pathBubbleSent = "themes/football/bb_sent_football_4.png",
                    pathBubbleReceived = "themes/football/bb_receive_football_4.png",
                    pathEnterChat = "themes/football/enter_sent_football_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#007AFF",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#BDDCFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#007AFF",
                    colBGEnterChat = "#BDDCFF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/football/theme_football_5.png",
                    pathBG = "themes/football/bg_football_5.png",
                    pathAvt = "themes/football/avt_football_5.png",
                    pathBubbleSent = "themes/football/bb_sent_football_5.png",
                    pathBubbleReceived = "themes/football/bb_receive_football_5.png",
                    pathEnterChat = "themes/football/enter_sent_football_5.png",
                    font = "fonts/NotoSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#F90400",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFFFFF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#F90400",
                    colBGEnterChat = "#FFFFFF",
                    colTextEnterChat = "#000000"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Anime",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/anime/theme_anime_1.png",
                    pathBG = "themes/anime/bg_anime_1.png",
                    pathAvt = "themes/anime/avt_anime_1.png",
                    pathBubbleSent = "themes/anime/bb_sent_anime_1.png",
                    pathBubbleReceived = "themes/anime/bb_receive_anime_1.png",
                    pathEnterChat = "themes/anime/enter_sent_anime_1.png",
                    font = "fonts/Podkova-VariableFont_wght.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#FF4400",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFCAB7",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#FF4400",
                    colBGEnterChat = "#FFCAB7",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/anime/theme_anime_2.png",
                    pathBG = "themes/anime/bg_anime_2.png",
                    pathAvt = "themes/anime/avt_anime_2.png",
                    pathBubbleSent = "themes/anime/bb_sent_anime_2.png",
                    pathBubbleReceived = "themes/anime/bb_receive_anime_2.png",
                    pathEnterChat = "themes/anime/enter_sent_anime_2.png",
                    font = "fonts/Martel-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#BFD3FF",
                    widthStroke = 1,
                    colMain = "#2563EB",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#BFD3FF",
                    colStrokeBBSent = "BFD3FF",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#2563EB",
                    colBGEnterChat = "#BFD3FF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/anime/theme_anime_3.png",
                    pathBG = "themes/anime/bg_anime_3.png",
                    pathAvt = "themes/anime/avt_anime_3.png",
                    pathBubbleSent = "themes/anime/bb_sent_anime_3.png",
                    pathBubbleReceived = "themes/anime/bb_receive_anime_3.png",
                    pathEnterChat = "themes/anime/enter_sent_anime_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#D90000",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFBABA",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#D90000",
                    colBGEnterChat = "#FFBABA",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/anime/theme_anime_4.png",
                    pathBG = "themes/anime/bg_anime_4.png",
                    pathAvt = "themes/anime/avt_anime_4.png",
                    pathBubbleSent = "themes/anime/bb_sent_anime_4.png",
                    pathBubbleReceived = "themes/anime/bb_receive_anime_4.png",
                    pathEnterChat = "themes/anime/enter_sent_anime_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#EA580C",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#F3F4F6",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#EA580C",
                    colBGEnterChat = "#F3F4F6",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/anime/theme_anime_5.png",
                    pathBG = "themes/anime/bg_anime_5.png",
                    pathAvt = "themes/anime/avt_anime_5.png",
                    pathBubbleSent = "themes/anime/bb_sent_anime_5.png",
                    pathBubbleReceived = "themes/anime/bb_receive_anime_5.png",
                    pathEnterChat = "themes/anime/enter_sent_anime_5.png",
                    font = "fonts/NotoSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#004E64",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#B8FFF6",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#004E64",
                    colBGEnterChat = "#B8FFF6",
                    colTextEnterChat = "#000000"
                ),
            )
        ),
        CategoryThemeModel(
            nameCategory = "Balloon",
            listTheme = listOf(
                ThemeMessModel(
                    id = 0,
                    pathThemePreview = "themes/balloon/theme_balloon_1.png",
                    pathBG = "themes/balloon/bg_balloon_1.png",
                    pathAvt = "themes/balloon/avt_balloon_1.png",
                    pathBubbleSent = "themes/balloon/bb_sent_balloon_1.png",
                    pathBubbleReceived = "themes/balloon/bb_receive_balloon_1.png",
                    pathEnterChat = "themes/balloon/enter_sent_balloon_1.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#D32570",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFB4D4",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#D32570",
                    colBGEnterChat = "#FFB4D4",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 1,
                    pathThemePreview = "themes/balloon/theme_balloon_2.png",
                    pathBG = "themes/balloon/bg_balloon_2.png",
                    pathAvt = "themes/balloon/avt_balloon_2.png",
                    pathBubbleSent = "themes/balloon/bb_sent_balloon_2.png",
                    pathBubbleReceived = "themes/balloon/bb_receive_balloon_2.png",
                    pathEnterChat = "themes/balloon/enter_sent_balloon_2.png",
                    font = "fonts/PTSans-Regular.ttf",
                    typeBubble = 1,
                    enableStroke = true,
                    colorStroke = "#C4FEC1",
                    widthStroke = 1,
                    colMain = "#085B03",
                    colStrokeBBReceived = "#000000",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#C4FEC1",
                    colStrokeBBSent = "C4FEC1",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#085B03",
                    colBGEnterChat = "#C4FEC1",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 2,
                    pathThemePreview = "themes/balloon/theme_balloon_3.png",
                    pathBG = "themes/balloon/bg_balloon_3.png",
                    pathAvt = "themes/balloon/avt_balloon_3.png",
                    pathBubbleSent = "themes/balloon/bb_sent_balloon_3.png",
                    pathBubbleReceived = "themes/balloon/bb_receive_balloon_3.png",
                    pathEnterChat = "themes/balloon/enter_sent_balloon_3.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#744577",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FBC2FF",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#744577",
                    colBGEnterChat = "#FBC2FF",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 3,
                    pathThemePreview = "themes/balloon/theme_balloon_4.png",
                    pathBG = "themes/balloon/bg_balloon_4.png",
                    pathAvt = "themes/balloon/avt_balloon_4.png",
                    pathBubbleSent = "themes/balloon/bb_sent_balloon_4.png",
                    pathBubbleReceived = "themes/balloon/bb_receive_balloon_4.png",
                    pathEnterChat = "themes/balloon/enter_sent_balloon_4.png",
                    font = "fonts/roboto.ttf",
                    typeBubble = 0,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#B47400",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#FFEAC3",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#B47400",
                    colBGEnterChat = "#FFEAC3",
                    colTextEnterChat = "#000000"
                ),
                ThemeMessModel(
                    id = 4,
                    pathThemePreview = "themes/balloon/theme_balloon_5.png",
                    pathBG = "themes/balloon/bg_balloon_5.png",
                    pathAvt = "themes/balloon/avt_balloon_5.png",
                    pathBubbleSent = "themes/balloon/bb_sent_balloon_5.png",
                    pathBubbleReceived = "themes/balloon/bb_receive_balloon_5.png",
                    pathEnterChat = "themes/balloon/enter_sent_balloon_5.png",
                    font = "fonts/NotoSans-Bold.ttf",
                    typeBubble = 2,
                    enableStroke = false,
                    colorStroke = "#FFFFFF",
                    widthStroke = 0,
                    colMain = "#014C43",
                    colStrokeBBReceived = "",
                    colTextBBReceived = "#000000",
                    colBGBBReceived = "#AEFFF5",
                    colStrokeBBSent = "",
                    colTextBBSent = "#FFFFFF",
                    colBGBBSent = "#014C43",
                    colBGEnterChat = "#AEFFF5",
                    colTextEnterChat = "#000000"
                ),
            )
        ),
    )
}